import type { Product, Entrepreneur, GeneralReview, Category } from "@/types"

export const categories: Category[] = [
  { id: "1", name: "Artesanías", slug: "artesanias" },
  { id: "2", name: "Comida", slug: "comida" },
  { id: "3", name: "Textiles", slug: "textiles" },
  { id: "4", name: "Joyería", slug: "joyeria" },
  { id: "5", name: "Decoración", slug: "decoracion" },
  { id: "6", name: "Servicios", slug: "servicios" },
]

export const products: Product[] = [
  {
    id: "1",
    name: "Collar de Plata Artesanal",
    price: 45000,
    image: "/placeholder-yyq3t.png",
    entrepreneur: "María González",
    category: "Joyería",
    location: "Bogotá",
    rating: 4.8,
    reviewCount: 23,
    slug: "collar-plata-artesanal",
  },
  {
    id: "2",
    name: "Mochila Wayuu Original",
    price: 120000,
    image: "/colorful-wayuu-bag.png",
    entrepreneur: "Carmen Uriana",
    category: "Textiles",
    location: "La Guajira",
    rating: 4.9,
    reviewCount: 45,
    slug: "mochila-wayuu-original",
  },
  {
    id: "3",
    name: "Café Orgánico de Montaña",
    price: 25000,
    image: "/colombian-organic-mountain-cafe.png",
    entrepreneur: "Carlos Ramírez",
    category: "Comida",
    location: "Huila",
    rating: 4.7,
    reviewCount: 67,
    slug: "cafe-organico-montana",
  },
  {
    id: "4",
    name: "Hamaca Artesanal",
    price: 85000,
    image: "/colorful-colombian-hammock.png",
    entrepreneur: "Ana Morales",
    category: "Artesanías",
    location: "Atlántico",
    rating: 4.6,
    reviewCount: 34,
    slug: "hamaca-artesanal",
  },
  {
    id: "5",
    name: "Mermelada de Frutas Exóticas",
    price: 18000,
    image: "/homemade-exotic-fruit-jam.png",
    entrepreneur: "Luis Herrera",
    category: "Comida",
    location: "Valle del Cauca",
    rating: 4.5,
    reviewCount: 28,
    slug: "mermelada-frutas-exoticas",
  },
  {
    id: "6",
    name: "Cerámica Decorativa",
    price: 35000,
    image: "/placeholder-vpl07.png",
    entrepreneur: "Rosa Jiménez",
    category: "Decoración",
    location: "Boyacá",
    rating: 4.4,
    reviewCount: 19,
    slug: "ceramica-decorativa",
  },
  {
    id: "7",
    name: "Sombrero Vueltiao",
    price: 65000,
    image: "/sombrero-vueltiao-tradicional.png",
    entrepreneur: "Pedro Martínez",
    category: "Artesanías",
    location: "Córdoba",
    rating: 4.8,
    reviewCount: 52,
    slug: "sombrero-vueltiao",
  },
  {
    id: "8",
    name: "Aretes de Tagua",
    price: 22000,
    image: "/colombian-tagua-earrings.png",
    entrepreneur: "Lucía Vargas",
    category: "Joyería",
    location: "Nariño",
    rating: 4.6,
    reviewCount: 31,
    slug: "aretes-tagua",
  },
]

export const entrepreneurs: Entrepreneur[] = [
  {
    id: "1",
    name: "María González",
    businessName: "Plata y Tradición",
    photo: "/colombian-woman-artisan-smiling.png",
    story:
      "Desde hace 15 años trabajo la plata siguiendo técnicas ancestrales que aprendí de mi abuela. Cada pieza cuenta una historia y lleva el amor de nuestras tradiciones.",
    slug: "maria-gonzalez",
    location: "Bogotá",
    whatsapp: "+573001234567",
  },
  {
    id: "2",
    name: "Carmen Uriana",
    businessName: "Wayuu Auténtico",
    photo: "/wayuu-woman-weaving.png",
    story:
      "Soy tejedora wayuu de cuarta generación. Cada mochila que tejo lleva los símbolos y colores de mi pueblo, preservando nuestra cultura milenaria.",
    slug: "carmen-uriana",
    location: "La Guajira",
    whatsapp: "+573007654321",
  },
  {
    id: "3",
    name: "Carlos Ramírez",
    businessName: "Café de las Montañas",
    photo: "/placeholder.svg?height=400&width=400",
    story:
      "Mi familia cultiva café orgánico en las montañas del Huila desde hace tres generaciones. Cada grano es seleccionado a mano con amor y dedicación.",
    slug: "carlos-ramirez",
    location: "Huila",
    whatsapp: "+573009876543",
  },
]

export const generalReviews: GeneralReview[] = [
  {
    id: "1",
    userName: "Andrea López",
    rating: 5,
    comment:
      "Increíble plataforma para encontrar productos únicos y apoyar emprendedores locales. La calidad es excepcional.",
    date: "2024-01-15",
  },
  {
    id: "2",
    userName: "Miguel Torres",
    rating: 4,
    comment:
      "Me encanta poder conectar directamente con los artesanos. Los productos tienen una calidad y autenticidad incomparable.",
    date: "2024-01-10",
  },
  {
    id: "3",
    userName: "Sofia Mendoza",
    rating: 5,
    comment: "Cada compra es una experiencia especial. Conocer la historia detrás de cada producto hace la diferencia.",
    date: "2024-01-08",
  },
  {
    id: "4",
    userName: "Roberto Silva",
    rating: 4,
    comment: "Excelente iniciativa para apoyar el emprendimiento local. Productos de alta calidad y precios justos.",
    date: "2024-01-05",
  },
]
